#!/usr/bin/env python3
"""Regenerate _projects/ from the repositories pinned on the GitHub profile.

Mirrors the pattern of scripts/update_publications.py and scripts/update_music.py:
fetch public data, write files, let the workflow commit them only when they
actually changed. Driven by .github/workflows/update-content.yml.

Pinned repositories are only exposed through GitHub's GraphQL API, which always
requires a token — unlike the REST endpoints the sibling scripts use. In CI the
workflow's GITHUB_TOKEN is enough (it only reads public data); locally, export
GITHUB_TOKEN=$(gh auth token).

Every file written here carries `generated: true`. Files without that marker are
left alone, so a hand-written project card can coexist with the pinned ones.

Env:
  GITHUB_TOKEN     required
  GITHUB_USER      defaults to github_username in _data/socials.yml
"""

from __future__ import annotations

import json
import os
import re
import sys
import urllib.error
import urllib.request

SOCIALS_FILE = "_data/socials.yml"
OUTPUT_DIR = "_projects"
GRAPHQL_URL = "https://api.github.com/graphql"
MAX_DESCRIPTION = 260

QUERY = """
query($login: String!) {
  user(login: $login) {
    pinnedItems(first: 6, types: REPOSITORY) {
      nodes {
        ... on Repository {
          name
          description
          url
          object(expression: "HEAD:README.md") { ... on Blob { text } }
        }
      }
    }
  }
}
"""


def load_username() -> str:
    """Read github_username out of _data/socials.yml (no yaml dependency)."""
    if os.environ.get("GITHUB_USER"):
        return os.environ["GITHUB_USER"]
    try:
        with open(SOCIALS_FILE, encoding="utf-8") as f:
            for line in f:
                m = re.match(r"^github_username:\s*(\S+)", line)
                if m:
                    return m.group(1).strip("\"'")
    except OSError as e:
        sys.exit(f"Could not read {SOCIALS_FILE}: {e}")
    sys.exit(f"No 'github_username' found in {SOCIALS_FILE}.")


def fetch_pinned(login: str, token: str) -> list[dict]:
    payload = json.dumps({"query": QUERY, "variables": {"login": login}}).encode()
    req = urllib.request.Request(
        GRAPHQL_URL,
        data=payload,
        headers={
            "Authorization": f"bearer {token}",
            "Content-Type": "application/json",
            "User-Agent": f"{login}-site-updater",
        },
    )
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            body = json.load(resp)
    except urllib.error.HTTPError as e:
        sys.exit(f"GitHub GraphQL returned {e.code}: {e.read()[:300]!r}")
    except urllib.error.URLError as e:
        sys.exit(f"Could not reach GitHub GraphQL: {e.reason}")

    if "errors" in body:
        sys.exit(f"GitHub GraphQL error: {body['errors']}")
    user = (body.get("data") or {}).get("user")
    if not user:
        sys.exit(f"No such GitHub user: {login}")
    return [n for n in user["pinnedItems"]["nodes"] if n]


def summarize_readme(text: str) -> str:
    """First real sentence of a README, skipping headings, badges and images.

    Repos often leave the GitHub description empty; the README's opening line is
    almost always the tagline we want instead.
    """
    for raw in text.splitlines():
        line = raw.strip()
        if not line:
            continue
        # Headings, images, badges, raw HTML, code fences, tables, lists.
        if line.startswith(("#", "!", "<", "```", "|", "-", "*", "=")):
            continue
        line = line.lstrip("> ").strip()  # blockquote taglines are common
        if not line or line.startswith(("[!", "![")):
            continue
        # Strip badge-only lines: [![alt](img)](href)
        if re.fullmatch(r"(\[!\[.*?\]\(.*?\)\]\(.*?\)\s*)+", line):
            continue
        # Markdown links -> their text; then drop leftover emphasis markers.
        line = re.sub(r"\[([^\]]+)\]\([^)]*\)", r"\1", line)
        line = re.sub(r"[*_`]", "", line).strip()
        if len(line) < 15:
            continue
        return line
    return ""


def truncate(text: str) -> str:
    text = " ".join(text.split())
    if len(text) <= MAX_DESCRIPTION:
        return text
    cut = text[:MAX_DESCRIPTION]
    stop = max(cut.rfind(". "), cut.rfind("; "))
    return (cut[: stop + 1] if stop > 80 else cut.rstrip() + "…").strip()


def yaml_quote(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render(repo: dict, importance: int) -> str:
    description = (repo.get("description") or "").strip()
    if not description:
        blob = repo.get("object") or {}
        description = summarize_readme(blob.get("text") or "")
    description = truncate(description) or "See the repository for details."

    return (
        "---\n"
        "# Generated by scripts/update_projects.py from the pinned repositories\n"
        "# on GitHub. Edits here are overwritten — change the repository's\n"
        "# description (or the first line of its README) instead.\n"
        "generated: true\n"
        "layout: page\n"
        f"title: {yaml_quote(repo['name'])}\n"
        f"description: {yaml_quote(description)}\n"
        f"importance: {importance}\n"
        f"github: {repo['url']}\n"
        f"redirect: {repo['url']}\n"
        "---\n"
    )


def slugify(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", name.lower()).strip("_")


def main() -> None:
    token = os.environ.get("GITHUB_TOKEN")
    if not token:
        sys.exit(
            "GITHUB_TOKEN is required (pinned repos are GraphQL-only).\n"
            "Locally: export GITHUB_TOKEN=$(gh auth token)"
        )

    login = load_username()
    print(f"Fetching pinned repositories for {login}")
    repos = fetch_pinned(login, token)
    if not repos:
        sys.exit(f"{login} has no pinned repositories — refusing to wipe {OUTPUT_DIR}/.")

    os.makedirs(OUTPUT_DIR, exist_ok=True)

    # Drop previously generated files so unpinned repos disappear. Anything
    # without the marker is hand-written and must survive.
    for name in os.listdir(OUTPUT_DIR):
        path = os.path.join(OUTPUT_DIR, name)
        if not name.endswith(".md"):
            continue
        with open(path, encoding="utf-8") as f:
            if re.search(r"^generated:\s*true\s*$", f.read(), re.M):
                os.remove(path)

    for index, repo in enumerate(repos, start=1):
        path = os.path.join(OUTPUT_DIR, f"{index}_{slugify(repo['name'])}.md")
        with open(path, "w", encoding="utf-8") as f:
            f.write(render(repo, index))
        source = "description" if (repo.get("description") or "").strip() else "README"
        print(f"  {repo['name']:<14} -> {path}  (description from {source})")

    print(f"Wrote {len(repos)} project card(s) to {OUTPUT_DIR}/")


if __name__ == "__main__":
    main()
