#!/usr/bin/env python3
"""Regenerate _data/music.yml from a NetEase Cloud Music artist page.

Mirrors the pattern of scripts/update_publications.py / bin/update_scholar_citations.py:
fetch public data, write a _data/*.yml file, let the workflow commit it only when
it actually changed. Uses only NetEase's *public* GET endpoints (no login/cookie),
so it can run unattended in CI. The live site build is separate — if a run fails,
the last good _data/music.yml stays committed and the page never breaks.

Artist id comes from the resolved NetEase artist link in _data/socials.yml
(https://163cn.tv/... -> music.163.com/artist?id=<ARTIST_ID>). Override with the
MUSIC_ARTIST_ID env var if it ever changes.
"""

import json
import os
import sys
import time
import urllib.parse
import urllib.request

ARTIST_ID = os.environ.get("MUSIC_ARTIST_ID", "32272234")
OUT_PATH = os.path.join(os.path.dirname(__file__), "..", "_data", "music.yml")

HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
        "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36"
    ),
    "Referer": "https://music.163.com/",
    "Cookie": "NMTID=1",
}


def _get(url):
    req = urllib.request.Request(url, headers=HEADERS)
    with urllib.request.urlopen(req, timeout=30) as resp:
        data = json.loads(resp.read().decode("utf-8"))
    code = data.get("code")
    if code != 200:
        raise RuntimeError(f"NetEase returned code={code} for {url}")
    return data


def fetch_songs(artist_id):
    """Return [{title, id}] for the artist's hot songs, newest first."""
    data = _get(f"https://music.163.com/api/artist/{artist_id}")
    songs = data.get("hotSongs") or []
    # hotSongs is roughly release-order; keep as returned but newest first.
    return [{"id": s["id"], "title": s["name"]} for s in songs]


def fetch_covers(song_ids):
    """Map song id -> {cover, album, year} via the song detail endpoint."""
    if not song_ids:
        return {}
    ids = urllib.parse.quote(json.dumps(song_ids))
    data = _get(f"https://music.163.com/api/song/detail?ids={ids}")
    out = {}
    for s in data.get("songs") or []:
        album = s.get("album") or s.get("al") or {}
        pic = album.get("picUrl") or ""
        year = ""
        pub = s.get("publishTime") or album.get("publishTime")
        if pub and pub > 0:
            # publishTime is unix ms; take the exact UTC year.
            year = str(time.gmtime(int(pub) / 1000).tm_year)
        out[s["id"]] = {"cover": pic, "album": album.get("name") or "", "year": year}
    return out


def build_entries(artist_id):
    songs = fetch_songs(artist_id)
    covers = fetch_covers([s["id"] for s in songs])
    entries = []
    for s in songs:
        meta = covers.get(s["id"], {})
        cover = meta.get("cover") or ""
        if cover:
            cover += "?param=512y512"  # ask the NetEase CDN for a sensible size
        subtitle_bits = [b for b in (meta.get("year"), "original") if b]
        entries.append(
            {
                "title": s["title"],
                "url": f"https://music.163.com/song?id={s['id']}",
                "cover": cover,
                "subtitle": " · ".join(subtitle_bits),
            }
        )
    return entries


def dump_yaml(entries):
    # JSON strings are valid YAML scalars, so json.dumps handles all escaping
    # (Chinese titles, quotes, colons) safely without a yaml dependency.
    lines = [
        "# Auto-generated by scripts/update_music.py from the NetEase artist page.",
        "# Do not edit by hand — the update-music workflow overwrites this file.",
        "# Newest first; the /music/ page renders them in this order.",
        "",
    ]
    for e in entries:
        lines.append(f"- title: {json.dumps(e['title'], ensure_ascii=False)}")
        lines.append(f"  url: {json.dumps(e['url'], ensure_ascii=False)}")
        lines.append(f"  cover: {json.dumps(e['cover'], ensure_ascii=False)}")
        if e["subtitle"]:
            lines.append(f"  subtitle: {json.dumps(e['subtitle'], ensure_ascii=False)}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main():
    try:
        entries = build_entries(ARTIST_ID)
    except Exception as exc:  # noqa: BLE001 — leave last-good file in place on failure
        print(f"❌ Failed to fetch music data: {exc}", file=sys.stderr)
        return 1
    if not entries:
        print("❌ No songs returned; leaving _data/music.yml untouched.", file=sys.stderr)
        return 1
    with open(OUT_PATH, "w", encoding="utf-8") as fh:
        fh.write(dump_yaml(entries))
    print(f"✅ Wrote {len(entries)} track(s) to _data/music.yml")
    for e in entries:
        print(f"   - {e['title']}  ({e['subtitle']})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
